In [36]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import Dataset

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [44]:
df = pd.DataFrame(np.random.rand(1000,4))
df['key']=[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199]*5
df

0         1         2         3  key
0    0.486032  0.888122  0.018709  0.476632    0
1    0.381126  0.792435  0.079900  0.477730    1
2    0.201873  0.042093  0.520917  0.649341    2
3    0.983704  0.957262  0.275142  0.782388    3
4    0.604102  0.087952  0.710132  0.649723    4
..        ...       ...       ...       ...  ...
995  0.256006  0.402414  0.119971  0.501209  195
996  0.813822  0.560728  0.496926  0.753087  196
997  0.773818  0.367845  0.012240  0.823490  197
998  0.283843  0.269048  0.323781  0.229416  198
999  0.097432  0.766578  0.875412  0.065886  199

[1000 rows x 5 columns]

In [45]:
df_ = df.groupby('key').agg(list).reset_index()
df_

key                                                  0  \
0      0  [0.4860324632700038, 0.13138110905072953, 0.79...   
1      1  [0.38112573572270936, 0.7041654838335211, 0.50...   
2      2  [0.2018725797762968, 0.4654179874358997, 0.555...   
3      3  [0.98370358520896, 0.8830150974025198, 0.06342...   
4      4  [0.6041018776696296, 0.12090278526607856, 0.68...   
..   ...                                                ...   
195  195  [0.27687663990666644, 0.9677340031601654, 0.97...   
196  196  [0.9505330136461019, 0.6926765203916163, 0.320...   
197  197  [0.6218062433876224, 0.4017089222970849, 0.436...   
198  198  [0.797244055018426, 0.93777520349951, 0.282186...   
199  199  [0.21333198654637886, 0.6147932486191304, 0.00...   

                                                     1  \
0    [0.8881219464705251, 0.20864671903342946, 0.38...   
1    [0.7924351517531779, 0.05415384418064495, 0.60...   
2    [0.042092976763622336, 0.7932457166435192, 0.8...   
3    [0.957261993337189, 0.40923672207278083, 0.972...   
4    [0.0879523979671677, 0.9325429293171718, 0.477...   
..                                                 ...   
195  [0.11774308403280809, 0.9621653409526403, 0.04...   
196  [0.7240618794010416, 0.3303441342686554, 0.584...   
197  [0.2255523952955656, 0.4126591799054342, 0.956...   
198  [0.10032849370618246, 0.08135955252703486, 0.6...   
199  [0.9791205160946261, 0.770696625437899, 0.9296...   

                                                     2  \
0    [0.01870871618575687, 0.10512015392532159, 0.1...   
1    [0.07989976125950249, 0.2676103631372241, 0.27...   
2    [0.5209174235653073, 0.5995503800410166, 0.786...   
3    [0.27514248438415445, 0.10116969933079989, 0.8...   
4    [0.7101322237118392, 0.3748823849808913, 0.422...   
..                                                 ...   
195  [0.09192920448322095, 0.9395040275506202, 0.74...   
196  [0.7850073797356213, 0.583830460476029, 0.0123...   
197  [0.5201474100682951, 0.5176609003644608, 0.884...   
198  [0.066511700338177, 0.937236572012475, 0.27442...   
199  [0.5670533174040615, 0.2355357903191172, 0.385...   

                                                     3  
0    [0.47663235931408454, 0.576920559298936, 0.713...  
1    [0.4777296529110592, 0.3570216083139893, 0.968...  
2    [0.6493408462941987, 0.6688332829720719, 0.925...  
3    [0.7823878324701936, 0.15069694529186994, 0.22...  
4    [0.6497234198678308, 0.7508467460990507, 0.372...  
..                                                 ...  
195  [0.10867006562432913, 0.5759881092777739, 0.19...  
196  [0.33213496718154356, 0.1790419929525512, 0.62...  
197  [0.009826029609842357, 0.9448291043447568, 0.4...  
198  [0.057084393502494835, 0.8298808025503668, 0.0...  
199  [0.18570704204822985, 0.476099591943419, 0.834...  

[200 rows x 5 columns]

In [46]:
df_.shape

(200, 5)

In [47]:
df_list = df_.columns
df_list

Index(['key', 0, 1, 2, 3], dtype='object')

In [48]:
ddd = []
for i , df_column in enumerate(df_list):
    # print(i , df_column)
    if df_column != 'key':
        print(i , df_column)
        ddd.append(np.array(df_[df_column].values.tolist()))

        pass
ddd[df_column].shape


1 0
2 1
3 2
4 3


(200, 5)

In [49]:
for i,item in enumerate(ddd):
    print(i , item.shape)

0 (200, 5)
1 (200, 5)
2 (200, 5)
3 (200, 5)


In [55]:
inputs = np.concatenate([item[:, None] for i,item in enumerate(ddd)],1).transpose(0,2,1)

In [56]:
inputs.shape

(200, 5, 4)

In [7]:
ddd0 = np.array(df_[0].values.tolist())
ddd1 = np.array(df_[1].values.tolist())
ddd2 = np.array(df_[2].values.tolist())
ddd3 = np.array(df_[3].values.tolist())
# ddd0
print(ddd0.shape)
print(ddd1.shape)
print(ddd2.shape)
print(ddd3.shape)

(5, 6)
(5, 6)
(5, 6)
(5, 6)


In [13]:
df_

key                                                  0  \
0    1  [0.6731811860322209, 0.1476257239321308, 0.871...   
1    2  [0.9536375637700576, 0.33502322523523465, 0.37...   
2    3  [0.33270422702604296, 0.12753097942000702, 0.0...   
3    4  [0.8964312026472319, 0.17078113216057345, 0.59...   
4    5  [0.6587724000754519, 0.5231119605016467, 0.261...   

                                                   1  \
0  [0.5375461857822328, 0.029529092646848443, 0.2...   
1  [0.5329293819520193, 0.21855430521817176, 0.35...   
2  [0.26722718119888433, 0.772721616871192, 0.994...   
3  [0.7240950146747527, 0.6156495863573007, 0.771...   
4  [0.40621649765957935, 0.8004554069054781, 0.50...   

                                                   2  \
0  [0.4210423543853091, 0.7116043535620618, 0.440...   
1  [0.6975406594541456, 0.3286524198132622, 0.043...   
2  [0.12255449326736767, 0.5353872466365606, 0.36...   
3  [0.23990373422275957, 0.6912593085979518, 0.78...   
4  [0.607546116664116, 0.7457508923707233, 0.5839...   

                                                   3  \
0  [0.9147234148180018, 0.9762978822444289, 0.361...   
1  [0.802916573668897, 0.325527991332605, 0.87953...   
2  [0.4749635847490915, 0.8372497098213663, 0.237...   
3  [0.09619986277958692, 0.7346933096747532, 0.40...   
4  [0.9183832335083929, 0.9924402598069133, 0.186...   

                                                   4  \
0  [0.10030829256499652, 0.5162785273712373, 0.30...   
1  [0.6369371018696514, 0.5776707735750692, 0.548...   
2  [0.5318877758191134, 0.5424177420703378, 0.242...   
3  [0.7747811492733371, 0.5051113012114129, 0.838...   
4  [0.42662247772414796, 0.8020975406588626, 0.65...   

                                                   5  \
0  [0.5512359531509987, 0.25268070031936873, 0.47...   
1  [0.9595386048238164, 0.45091689215328135, 0.81...   
2  [0.3411162320929908, 0.22009471807526082, 0.90...   
3  [0.6744445198470868, 0.05825418235856006, 0.04...   
4  [0.8548592861829323, 0.7986386074650275, 0.549...   

                                                   6  \
0  [0.9232648855402945, 0.5345208351523947, 0.513...   
1  [0.15158398794179118, 0.34513317097781837, 0.7...   
2  [0.32802378616968, 0.707001387151652, 0.695774...   
3  [0.22349596666962823, 0.3940955106967269, 0.38...   
4  [0.042901314765363185, 0.9796857698555895, 0.6...   

                                                   7  
0  [0.6773393751399063, 0.6064520877673034, 0.388...  
1  [0.8470609270047958, 0.05845584755148703, 0.31...  
2  [0.07285956342623046, 0.3497230744671741, 0.05...  
3  [0.4883399517760324, 0.8477621952845804, 0.682...  
4  [0.03755065206357466, 0.7823901225992101, 0.36...

In [14]:
inputs = np.concatenate([
            ddd0[:, None], 
            ddd1[:, None], 
            ddd2[:, None], 
            ddd3[:, None]
        ], 1).transpose(0, 2, 1)
inputs.shape

(5, 6, 4)

In [62]:
from torch.utils.data import DataLoader
train_loader = DataLoader(
    inputs,
    batch_size=32,
    shuffle=True,
    drop_last=False,
    num_workers=4,
    pin_memory=True,
)

In [63]:
for data in train_loader:
    print('ffff')

ffff
ffff
ffff
ffff
ffff
ffff
ffff


In [64]:
for i,data in enumerate(train_loader):
    print(i,data.shape,type(data))

0 torch.Size([32, 5, 4]) <class 'torch.Tensor'>
1 torch.Size([32, 5, 4]) <class 'torch.Tensor'>
2 torch.Size([32, 5, 4]) <class 'torch.Tensor'>
3 torch.Size([32, 5, 4]) <class 'torch.Tensor'>
4 torch.Size([32, 5, 4]) <class 'torch.Tensor'>
5 torch.Size([32, 5, 4]) <class 'torch.Tensor'>
6 torch.Size([8, 5, 4]) <class 'torch.Tensor'>


In [10]:
torch.tensor(inputs,dtype=torch.float)

tensor([[[6.7318e-01, 5.3755e-01, 4.2104e-01, 9.1472e-01],
         [1.4763e-01, 2.9529e-02, 7.1160e-01, 9.7630e-01],
         [8.7160e-01, 2.1576e-01, 4.4035e-01, 3.6114e-01],
         [2.1846e-01, 4.0407e-01, 7.6042e-01, 5.9375e-01],
         [8.0208e-01, 7.7147e-01, 3.3025e-02, 5.8014e-01],
         [6.2082e-01, 5.1143e-01, 7.4522e-01, 7.5719e-01]],

        [[9.5364e-01, 5.3293e-01, 6.9754e-01, 8.0292e-01],
         [3.3502e-01, 2.1855e-01, 3.2865e-01, 3.2553e-01],
         [3.7862e-01, 3.5375e-01, 4.3963e-02, 8.7954e-01],
         [7.2438e-01, 4.5984e-01, 6.0289e-02, 8.6096e-01],
         [7.8195e-01, 1.5642e-01, 5.3667e-01, 5.6395e-01],
         [8.0178e-01, 8.9625e-01, 8.5012e-01, 6.2213e-01]],

        [[3.3270e-01, 2.6723e-01, 1.2255e-01, 4.7496e-01],
         [1.2753e-01, 7.7272e-01, 5.3539e-01, 8.3725e-01],
         [5.6088e-04, 9.9432e-01, 3.6681e-01, 2.3752e-01],
         [4.5309e-01, 8.0276e-01, 8.9255e-01, 8.5733e-01],
         [5.8063e-01, 5.4414e-01, 7.4202e-01, 8.5401

In [11]:
inputs[1,0]

array([0.95363756, 0.53292938, 0.69754066, 0.80291657])

In [12]:
data={
    "kkk":
}

SyntaxError: invalid syntax (341350897.py, line 3)

In [ ]:
df.shape

(10, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       10 non-null     float64
 1   1       10 non-null     float64
 2   2       10 non-null     float64
 3   3       10 non-null     float64
dtypes: float64(4)
memory usage: 448.0 bytes


In [ ]:
s = df[1]

In [ ]:
s.value_counts()

1
0.230321    1
0.615461    1
0.778536    1
0.644676    1
0.101991    1
0.770965    1
0.271527    1
0.140942    1
0.371502    1
0.354343    1
Name: count, dtype: int64

In [ ]:
s

0    0.230321
1    0.615461
2    0.778536
3    0.644676
4    0.101991
5    0.770965
6    0.271527
7    0.140942
8    0.371502
9    0.354343
Name: 1, dtype: float64

In [ ]:
df[[1, 2]]

1         2
0  0.230321  0.524121
1  0.615461  0.383512
2  0.778536  0.345850
3  0.644676  0.736874
4  0.101991  0.551155
5  0.770965  0.446356
6  0.271527  0.258886
7  0.140942  0.486358
8  0.371502  0.167616
9  0.354343  0.616503

In [ ]:
df.columns()


AttributeError: 'list' object has no attribute 'columns'