In [17]:
import torch.nn as nn
import torch

In [18]:
a = torch.rand(3)
a

tensor([0.1897, 0.2409, 0.4653])

In [19]:
a.requires_grad_()


tensor([0.1897, 0.2409, 0.4653], requires_grad=True)

In [20]:
p = torch.softmax(a,dim = 0)
p

tensor([0.2967, 0.3124, 0.3909], grad_fn=<SoftmaxBackward0>)

In [ ]:
p.backward(retain_graph=True)

In [ ]:
p.backward()