In [4]:
import numpy as np
from itertools import chain


In [5]:
index_gaolu     = range(1, 4, 1)
index_gaolu     = range(7, 9, 1)
index_gaolu_combined = list(chain(
                        range(1, 4, 1), 
                        range(7, 9, 1)
                        ))
print(index_gaolu_combined)


[1, 2, 3, 7, 8]


In [3]:
a=np.array([1,2,3])
b=np.array([11,22,33])
c=np.array([44,55,66])
np.concatenate((a,b,c),axis=0)  
# 默认情况下，axis=0可以不写
# #对于一维数组拼接，axis的值不影响最后的结果


array([ 1,  2,  3, 11, 22, 33, 44, 55, 66])

In [4]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,21,31],[7,8,9]])
np.concatenate((a,b),axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 21, 31],
       [ 7,  8,  9]])

In [5]:
np.concatenate((a,b),axis=1)  #axis=1表示对应行的数组进行拼接


array([[ 1,  2,  3, 11, 21, 31],
       [ 4,  5,  6,  7,  8,  9]])

In [6]:
c = np.concatenate((a[:,None],b[:,None]),axis=1)
print(a.shape,b.shape,c.shape,a[:,None].shape,b[:,None].shape)


(2, 3) (2, 3) (2, 2, 3) (2, 1, 3) (2, 1, 3)


In [7]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,21,31],[7,8,9]])
print(a)
print(a.shape)
print(a[:, None])
print(a[:, None].shape)
c = np.concatenate((a,b),axis=1)
print(c)
print(c.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)
[[ 1  2  3 11 21 31]
 [ 4  5  6  7  8  9]]
(2, 6)


In [8]:
x_train=np.array([[1,2,3],[4,5,6]])
y_train=np.array([[11,21,31],[7,8,9]])
print(x_train)
print(y_train)


x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
y_train = np.reshape(y_train, (y_train.shape[0], x_train.shape[1],  1))
print(x_train.shape,y_train.shape)

print(x_train)
print(y_train)

c = np.concatenate((x_train,y_train),axis=2)
print(c)
print(c.shape)





[[1 2 3]
 [4 5 6]]
[[11 21 31]
 [ 7  8  9]]
(2, 3, 1) (2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[11]
  [21]
  [31]]

 [[ 7]
  [ 8]
  [ 9]]]
[[[ 1 11]
  [ 2 21]
  [ 3 31]]

 [[ 4  7]
  [ 5  8]
  [ 6  9]]]
(2, 3, 2)


In [9]:
x_train=np.array([[1,2,3],[4,5,6]])
x_train.reshape(6)


array([1, 2, 3, 4, 5, 6])