In [1]:
import torch.nn as nn
import torch

In [2]:
a = torch.randn(3,4,2,3)

In [3]:
print(a)

tensor([[[[-6.5707e-02,  4.4925e-01, -5.3509e-01],
          [-1.7973e+00, -1.9812e-01,  9.1210e-01]],

         [[ 1.1078e-01,  6.4443e-01,  2.7986e-01],
          [ 1.4112e-01,  7.8976e-01, -5.6341e-01]],

         [[ 1.0225e+00, -2.9908e-01,  2.2995e-01],
          [ 8.8057e-01, -2.0353e+00, -2.8502e-01]],

         [[-9.3436e-01,  3.2362e-01, -5.3147e-01],
          [-4.2671e-01, -4.9318e-01,  2.8445e-01]]],


        [[[ 6.9194e-01,  9.9071e-01, -4.7287e-01],
          [-1.7278e+00,  5.7851e-01, -7.5075e-01]],

         [[ 1.1858e-03, -1.7238e+00, -3.3816e-01],
          [ 8.4382e-01,  3.7571e-01,  1.4247e+00]],

         [[ 1.1689e+00, -1.7183e+00, -3.8212e-01],
          [-1.5501e+00,  2.8011e-01,  6.9346e-01]],

         [[ 1.5766e+00, -4.4111e-01, -1.6615e+00],
          [ 6.4444e-01, -8.1634e-01, -5.0276e-01]]],


        [[[ 1.2580e+00,  1.0873e+00,  5.4856e-01],
          [-1.6559e-01, -1.6025e+00,  1.0045e+00]],

         [[ 6.4811e-01, -3.9348e-01,  2.0162e+00],
         

In [4]:
a[1]

tensor([[[ 6.9194e-01,  9.9071e-01, -4.7287e-01],
         [-1.7278e+00,  5.7851e-01, -7.5075e-01]],

        [[ 1.1858e-03, -1.7238e+00, -3.3816e-01],
         [ 8.4382e-01,  3.7571e-01,  1.4247e+00]],

        [[ 1.1689e+00, -1.7183e+00, -3.8212e-01],
         [-1.5501e+00,  2.8011e-01,  6.9346e-01]],

        [[ 1.5766e+00, -4.4111e-01, -1.6615e+00],
         [ 6.4444e-01, -8.1634e-01, -5.0276e-01]]])

In [5]:
a.type()

'torch.FloatTensor'

In [6]:
type(a)

torch.Tensor

In [7]:
a.numel()

72

In [8]:
a.size()

torch.Size([3, 4, 2, 3])

In [9]:
a.shape

torch.Size([3, 4, 2, 3])

In [10]:
a.dim()

4

In [11]:
torch.zeros([4,2,3])

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [12]:
b = torch.rand(3,3)
b

tensor([[0.2492, 0.3835, 0.9990],
        [0.9487, 0.3831, 0.1475],
        [0.1085, 0.2990, 0.2597]])

In [13]:
torch.rand_like(b)

tensor([[0.6552, 0.6909, 0.8869],
        [0.6379, 0.3294, 0.5319],
        [0.9580, 0.4146, 0.9964]])

In [14]:
torch.randn(3,3)

tensor([[ 0.2571,  0.2668,  1.0001],
        [ 0.7146,  1.3894,  0.0361],
        [ 0.4643, -0.5282,  0.1904]])

In [15]:
torch.full([2,3],0)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
torch.linspace(0,10,steps=7)

tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])

In [18]:
torch.logspace(1,2,steps=6)

tensor([ 10.0000,  15.8489,  25.1189,  39.8107,  63.0957, 100.0000])

In [19]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [20]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
a = torch.rand(4,3,28,28)

In [23]:
a[0].shape

torch.Size([3, 28, 28])

In [24]:
a[0,0].shape

torch.Size([28, 28])

In [25]:
a[0,0,3].shape

torch.Size([28])

In [26]:
a[0,0,3,24].shape

torch.Size([])

In [27]:
a[0,0,3,24]

tensor(0.5456)

In [28]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [29]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [31]:
x = torch.rand(3,3)
x

tensor([[0.1289, 0.3836, 0.1925],
        [0.6640, 0.3041, 0.7646],
        [0.5540, 0.2031, 0.5823]])

In [33]:
mask = x.ge(0.5)
mask

tensor([[False, False, False],
        [ True, False,  True],
        [ True, False,  True]])