In [ ]:
import torch.nn as nn
import torch

In [ ]:
a = torch.rand(3,2,5,5)
a

In [ ]:
a.shape

In [ ]:
a.view(3,2,5*5)

In [ ]:
a.view(3,2,5*5).shape

In [ ]:
a.view(3*2,5*5)

In [ ]:
a.view(3*2,5*5).shape

In [ ]:
a.unsqueeze(0).shape

In [ ]:
a.unsqueeze(-1).shape

In [ ]:
a.unsqueeze(0)

In [37]:
b = torch.rand(2)

In [38]:
f = torch.rand(4,2,5,5)

In [40]:
c = b.unsqueeze(-1).unsqueeze(-1).unsqueeze(0)
d =c

In [41]:
c.shape

torch.Size([1, 2, 1, 1])

In [42]:
c.squeeze(2).shape

torch.Size([1, 2, 1])

In [43]:
d.shape

torch.Size([1, 2, 1, 1])

In [47]:
d.expand(3,2,5,5)

tensor([[[[0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444]],

         [[0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368]]],


        [[[0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444]],

         [[0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
    

In [45]:
d.expand(3,2,5,5).shape

torch.Size([3, 2, 5, 5])

In [46]:
a.shape

torch.Size([3, 2, 5, 5])

In [48]:
d.repeat(3,2,5,5)

tensor([[[[0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444]],

         [[0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368]],

         [[0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444],
          [0.5444, 0.5444, 0.5444, 0.5444, 0.5444]],

         [[0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
          [0.0368, 0.0368, 0.0368, 0.0368, 0.0368],
      

In [49]:
a.shape

torch.Size([3, 2, 5, 5])

In [50]:
a.transpose(1,2).shape

torch.Size([3, 5, 2, 5])

In [52]:
a = torch.ones(8)
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
b = a.view(2,4)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [64]:
b.norm(1,dim = 1)

tensor([4., 4.])

In [78]:
a=torch.arange(0,10).view(2,5)
a

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [79]:
a.argmax(dim = 0)

tensor([1, 1, 1, 1, 1])